#!/bin/bash
# Holds tests/shell-cases.ts to what hooks/lib/shell_parse.py reads.
# Run directly: ./test-shell-parity.sh          (check)
#               ./test-shell-parity.sh --write  (regenerate the fixture)
#
# $.workbench.parseShell (hooks/mods/shell.ts) is the TypeScript reader the
# guard ports move onto. shell_parse.py stays behind the bash guards until
# they are ported, and the two must read the same corpus the same way. So:
#
#   1. this script runs hooks/test-parser-differential.sh with
#      PARSER_CASES_OUT set, which writes every command of its corpus;
#   2. it reads each command through shell_parse.py as the guards do: the
#      lines, the statements, the pipeline stages, strip_noop() on each stage,
#      and the heredoc bodies. A redirect operator and its target are taken
#      out of the words, because the TS reader reports redirects apart;
#   3. it renders the readings as tests/shell-cases.ts and compares that with
#      the committed file.
#
# tests/shell.test.ts then holds parseShell to every case, and lists each
# case where the two differ with the reason the TS reading is the safer one.
# A change to either parser turns one side red until they agree again.

set -u
HOOKS_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HOOKS_DIR/.." && pwd)"
FIXTURE="$ROOT/tests/shell-cases.ts"
PASS=0
FAIL=0

# Without jq the corpus cannot be recorded, so the fixture cannot be checked.
# A skip would pass a stale fixture, so this fails instead.
if ! command -v jq >/dev/null 2>&1; then
  echo "  ❌ jq is not on PATH, so tests/shell-cases.ts cannot be checked against shell_parse.py"
  exit 1
fi

SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/shell-parity.XXXXXX")"
trap 'rm -rf "$SANDBOX"' EXIT

CASES="$SANDBOX/cases.jsonl"
if ! PARSER_CASES_OUT="$CASES" bash "$HOOKS_DIR/test-parser-differential.sh" >"$SANDBOX/differential.log" 2>&1; then
  echo "  ❌ hooks/test-parser-differential.sh failed, so its corpus is no oracle:"
  tail -5 "$SANDBOX/differential.log"
  exit 1
fi

READINGS="$SANDBOX/readings.json"
python3 - "$HOOKS_DIR/lib" "$CASES" >"$READINGS" <<'PY'
import json
import sys

sys.path.insert(0, sys.argv[1])
from shell_parse import base, split_statements, strip_noop, token_lines_ex

REDIRECTS = {"<", ">", ">>", "<<", "<<<", "<>", ">|", "&>", "&>>", ">&", "<&"}


def words_of(stage):
    """The stage's tokens with each redirect operator, its target, and a file
    descriptor written before it taken out."""
    out = []
    skip = False
    for i, token in enumerate(stage):
        if skip:
            skip = False
            continue
        if token in REDIRECTS:
            skip = True
            continue
        if token.isdigit() and i + 1 < len(stage) and stage[i + 1] in REDIRECTS:
            continue
        out.append(token)
    return out


cases = []
seen = set()
with open(sys.argv[2]) as handle:
    for row in handle:
        case = json.loads(row)
        # One command reaches several guards. It is read once.
        if case["command"] in seen:
            continue
        seen.add(case["command"])
        lines, exact, bodies = token_lines_ex(case["command"])
        statements = []
        for line in lines:
            for stages in split_statements(line):
                for stage in stages:
                    words = strip_noop(words_of(stage))
                    if words:
                        statements.append({"name": base(words[0]), "args": words[1:]})
        cases.append({
            "label": case["label"],
            "command": case["command"],
            "exact": exact,
            "statements": statements,
            "bodies": sorted(body for texts in bodies.values() for body in texts),
        })
json.dump(cases, sys.stdout, ensure_ascii=True, indent=2)
PY

render() {
  cat <<'EOF'
// GENERATED by hooks/test-shell-parity.sh --write. Do not edit by hand.
//
// Every command of hooks/test-parser-differential.sh, as hooks/lib/
// shell_parse.py reads it: each pipeline stage after strip_noop(), with its
// redirects taken out, and the heredoc bodies. tests/shell.test.ts holds
// $.workbench.parseShell to them.

EOF
  printf 'export const PARSER_CASES = '
  cat "$READINGS"
  printf '\n'
}
render >"$SANDBOX/shell-cases.ts"

if [ "${1:-}" = "--write" ]; then
  cp "$SANDBOX/shell-cases.ts" "$FIXTURE"
  echo "wrote $FIXTURE"
  exit 0
fi

ok() { PASS=$((PASS + 1)); echo "  ✅ $1"; }
no() { FAIL=$((FAIL + 1)); echo "  ❌ $1"; }

echo "the differential corpus reaches the fixture:"
COUNT=$(jq 'length' "$READINGS")
# The differential suite reads about forty commands. A count far below that
# means the recorder lost its hook into the suite, and an empty fixture would
# agree with any reader.
if [ "$COUNT" -ge 25 ]; then ok "$COUNT commands recorded"; else no "only $COUNT commands recorded"; fi
if jq -e 'any(.[]; .bodies != [])' "$READINGS" >/dev/null; then
  ok "the cases hold heredoc bodies"
else
  no "no case holds a heredoc body"
fi
if jq -e 'all(.[]; .command | contains("/tmp/pdiff") | not)' "$READINGS" >/dev/null; then
  ok "no case names the run's own sandbox"
else
  no "a case names the run's own sandbox, so the fixture changes on every run"
fi

echo "the committed fixture is current:"
if cmp -s "$SANDBOX/shell-cases.ts" "$FIXTURE"; then
  ok "tests/shell-cases.ts matches shell_parse.py"
else
  no "tests/shell-cases.ts is stale: run hooks/test-shell-parity.sh --write, then claude plugin test"
  diff "$FIXTURE" "$SANDBOX/shell-cases.ts" | head -20
fi

echo
echo "$PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
