#!/bin/bash
# Holds tests/brief-cases.ts to what the bash dispatch gate actually does.
# Run directly: ./test-brief-parity.sh          (check)
#               ./test-brief-parity.sh --write  (regenerate the fixture)
#
# $.workbench.briefCheck() (hooks/mods/brief.ts) is a TypeScript port of the
# prompt half of hooks/agent-dispatch-gate.sh, and briefSlots() a port of the
# records in hooks/lib/brief-template.sh. A port drifts the way every copy in
# this repo has drifted, so the two are held together through one fixture:
#
#   1. this script runs hooks/test-agent-dispatch-gate.sh with
#      BRIEF_CASES_OUT set, which writes every prompt case it judges, with the
#      verdict and the missing slots the gate gave it;
#   2. it reads the slot records from hooks/lib/brief-template.sh;
#   3. it renders both as tests/brief-cases.ts and compares that with the
#      committed file.
#
# tests/workbench.test.ts then runs briefCheck() over every case and briefSlots()
# against the records. So a change to the gate or the template turns this
# script red until the fixture is regenerated, and the regenerated fixture turns
# the TypeScript test red until the port agrees.

set -u
HOOKS_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HOOKS_DIR/.." && pwd)"
FIXTURE="$ROOT/tests/brief-cases.ts"
PASS=0
FAIL=0

if ! command -v jq >/dev/null 2>&1; then
  echo "SKIP: jq not on PATH"
  exit 0
fi

SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/brief-parity.XXXXXX")"
trap 'rm -rf "$SANDBOX"' EXIT

CASES="$SANDBOX/cases.jsonl"
if ! BRIEF_CASES_OUT="$CASES" bash "$HOOKS_DIR/test-agent-dispatch-gate.sh" >"$SANDBOX/gate.log" 2>&1; then
  echo "  ❌ hooks/test-agent-dispatch-gate.sh failed, so its verdicts are no oracle:"
  tail -5 "$SANDBOX/gate.log"
  exit 1
fi

# shellcheck source=hooks/lib/brief-template.sh
. "$HOOKS_DIR/lib/brief-template.sh"
SLOTS="$SANDBOX/slots.jsonl"
for record in "${WORKBENCH_BRIEF_SLOTS[@]}"; do
  jq -nc --arg header "$(brief_slot_field "$record" 1)" --arg description "$(brief_slot_field "$record" 3)" \
    '{header: $header, description: $description}' >>"$SLOTS"
done

# -a escapes every non-ASCII character, so the exotic spaces the gate cases
# carry are visible in the fixture instead of invisible.
render() {
  cat <<'EOF'
// GENERATED by hooks/test-brief-parity.sh --write. Do not edit by hand.
//
// Every prompt case of hooks/test-agent-dispatch-gate.sh, with the verdict the
// bash gate gave it, and the slot records of hooks/lib/brief-template.sh.
// tests/workbench.test.ts holds $.workbench.briefCheck() and briefSlots() to
// them.

EOF
  printf 'export const GATE_SLOTS = '
  jq -a -s '.' "$SLOTS"
  printf '\nexport const GATE_CASES = '
  jq -a -s '.' "$CASES"
}
render >"$SANDBOX/brief-cases.ts"

if [ "${1:-}" = "--write" ]; then
  cp "$SANDBOX/brief-cases.ts" "$FIXTURE"
  echo "wrote $FIXTURE"
  exit 0
fi

ok() { PASS=$((PASS + 1)); echo "  ✅ $1"; }
no() { FAIL=$((FAIL + 1)); echo "  ❌ $1"; }

echo "the gate's cases reach the fixture:"
COUNT=$(grep -c . "$CASES")
# The gate suite judges about sixty prompts. A count far below that means the
# recorder lost its hook into the suite, and an empty fixture would agree with
# any port.
if [ "$COUNT" -ge 40 ]; then ok "$COUNT prompt cases recorded"; else no "only $COUNT prompt cases recorded"; fi
if jq -e -s 'any(.[]; .isComplete) and any(.[]; .isComplete | not)' "$CASES" >/dev/null; then
  ok "the cases hold both verdicts"
else
  no "the cases hold only one verdict"
fi
for slot in "Workdir:" "Goal:" "Context:" "Constraints:" "Acceptance:" "Done when:"; do
  if jq -e -s --arg s "$slot" 'any(.[]; .missing == [$s])' "$CASES" >/dev/null; then
    ok "a case misses $slot alone"
  else
    no "no case misses $slot alone"
  fi
done

echo "the committed fixture is current:"
if cmp -s "$SANDBOX/brief-cases.ts" "$FIXTURE"; then
  ok "tests/brief-cases.ts matches the gate and the template"
else
  no "tests/brief-cases.ts is stale: run hooks/test-brief-parity.sh --write, then claude plugin test"
  diff "$FIXTURE" "$SANDBOX/brief-cases.ts" | head -20
fi

echo
echo "$PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
