// The six-slot brief, as $.workbench.briefSlots() and $.workbench.briefCheck()
// answer it: a port of hooks/lib/brief-template.sh and of the prompt half of
// hooks/agent-dispatch-gate.sh, branches (f) and (g) and the slot check.
//
// The verdict must be the gate's, case for case. tests/brief-cases.ts holds
// every prompt case of hooks/test-agent-dispatch-gate.sh with the verdict the
// gate gave it, generated by hooks/test-brief-parity.sh, and
// tests/workbench.test.ts runs this check over the same list.
//
// Whitespace is the gate's ASCII set, never \s: whether NBSP is whitespace
// depends on the C library under grep, so the gate lists five characters, and
// \s here would take NBSP and U+3000 as spaces where the gate does not. Newline
// is absent for grep's reason: the gate matches within one line, so the prompt
// is split on \n and every pattern runs on one line. JavaScript's ^ and $ under
// the m flag also stop at \r, U+2028 and U+2029, which grep does not, so no
// pattern here uses the m flag.
//
// Pure functions only: the engine follows `$` into no imported function.

import type { WorkbenchBriefCheck, WorkbenchBriefSlot } from '../../types'

const WS = ' \\t\\r\\v\\f'

// Order is the template's order, as the gate's deny message lists the slots.
const SLOTS: readonly (WorkbenchBriefSlot & { pattern: RegExp })[] = [
  ['Workdir:', 'absolute path of the tree to work in, and the branch or worktree if one was settled'],
  ['Goal:', 'one or two sentences, measurable'],
  ['Context:', 'why the task exists, and what the agent cannot derive'],
  ['Constraints:', 'hard limits, or none'],
  ['Acceptance:', 'the criteria the work is graded against, one per line'],
  ['Done when:', 'observable finish line'],
].map(([header, description]) => ({
  header: header as string,
  description: description as string,
  pattern: new RegExp(`^[${WS}]*${(header as string).replace(' ', `[${WS}]+`)}`, 'i'),
}))

export const BRIEF_SLOTS: readonly WorkbenchBriefSlot[] = SLOTS.map(({ header, description }) => ({ header, description }))

const NONBLANK = new RegExp(`[^${WS}]`)
const ITEM_ID = new RegExp(`^[${WS}]*Item ID:[${WS}]*[0-9]+[${WS}]*$`)
const REPO_SWEEP = new RegExp(`^[${WS}]*Repo sweep:[${WS}]*[^${WS}/]+/[^${WS}/]+[${WS}]*$`)

// The gate's verdict on one prompt. A prompt with no character outside the
// ASCII set is blank, and the gate lets it through; so does a prompt whose
// one non-blank line is a machine-built shape. Every other prompt is a brief,
// complete when all six headers open a line.
export function checkBrief(prompt: string): WorkbenchBriefCheck {
  const lines = prompt.split('\n')
  const filled = lines.filter(line => NONBLANK.test(line))
  if (filled.length === 0) return { isComplete: true, missing: [], shape: 'blank' }
  if (filled.length === 1) {
    if (lines.some(line => ITEM_ID.test(line))) return { isComplete: true, missing: [], shape: 'item-id' }
    if (lines.some(line => REPO_SWEEP.test(line))) return { isComplete: true, missing: [], shape: 'repo-sweep' }
  }
  const missing = SLOTS.filter(slot => !lines.some(line => slot.pattern.test(line))).map(slot => slot.header)
  return { isComplete: missing.length === 0, missing, shape: 'brief' }
}
